Original-Server:
    allow: 
        - 192.168.1.0/24
        - 192.168.2.0/24


BalanceHub:
    listen: 5000
    algorithm: "Least-Connected"
    access-logs: true
    access-logs-path: /var/log
    caching: true
    cache-duration: 3000
    db-path: ''

        

    