Original-Server:
    allow: 
        - 192.168.1.0/24
        - 192.168.2.0/24
        - 127.0.0.0/

BalanceHub:
    listen: 5000
    algorithm: "Least-Connected"
    access-logs-path: ./logs
    db-path: ''
    redis-server: 
        ip: 127.0.0.1
        port: 6379
        db: 0
        password: ''
        caching: true
        cache-duration: 900